import {NgModule} from '@angular/core';

import {
  MatMenuModule,
  MatProgressSpinnerModule,
  MatExpansionModule,
  MatPaginatorModule,
  MatInputModule,
  MatGridListModule,
  MatTabsModule,
  MatButtonModule,
  MatCheckboxModule,
  MatSidenavModule,
  MatToolbarModule,
  MatCardModule,
  MatSelectModule,
  MatIconModule,
  MatDialogModule,
  MatSnackBarModule,
  MatTooltipModule,
  MatListModule,
  MatButtonToggleModule,
  MatTableModule
} from '@angular/material';

@NgModule({
  imports: [
    MatMenuModule,
    MatProgressSpinnerModule,
    MatExpansionModule,
    MatPaginatorModule,
    MatButtonModule,
    MatCheckboxModule,
    MatSidenavModule,
    MatToolbarModule,
    MatCardModule,
    MatCardModule,
    MatTabsModule,
    MatGridListModule,
    MatInputModule,
    MatSelectModule,
    MatIconModule,
    MatDialogModule,
    MatSnackBarModule,
    MatTooltipModule,
    MatListModule,
    MatButtonToggleModule,
    MatTableModule
  ],
  exports: [
    MatMenuModule,
    MatProgressSpinnerModule,
    MatExpansionModule,
    MatPaginatorModule,
    MatButtonModule,
    MatCheckboxModule,
    MatSidenavModule,
    MatToolbarModule,
    MatCardModule,
    MatCardModule,
    MatTabsModule,
    MatGridListModule,
    MatInputModule,
    MatSelectModule,
    MatIconModule,
    MatDialogModule,
    MatSnackBarModule,
    MatTooltipModule,
    MatListModule,
    MatButtonToggleModule,
    MatTableModule
  ],
})

export class MaterialModule { }
